export const KILLERS = [
    "Piégeur",
    "Spectre",
    "Montagnard",
    "Infirmière",
    "Silhouette",
    "Harpie",
    "Docteur",
    "Chasseuse",
    "Cannibale",
    "Cauchemar",
    "Cochon",
    "Clown",
    "Esprit",
    "Légion",
    "Épidémie",
    "Ghost Face",
    "Démogorgon",
    "Oni",
    "Lance-Mort",
    "Bourreau",
    "Fléau",
    "Jumeaux",
    "Farceur",
    "Némésis",
    "Cénobite",
    "Artiste",
    "Onryō",
    "Dragage",
    "Mastermind",
    "Chevalier",
    "Marchande de crânes",
    "Singularité",
    "Xénomorphe",
    "Brave Gars",
    "Inconnu",
    "Liche",
    "Seigneur des Ténèbres",
    "Maîtresse des Molosses",
    "Le Premier",
] as const;
// Verified list against official French localization.
// Dredge -> Dragage (official)
// Houndmaster -> Maîtresse des Molosses (official)

export const KILLER_IMAGES: Record<string, string> = {
    "Piégeur": "/killers/K01_TheTrapper_Portrait.webp",
    "Spectre": "/killers/K02_TheWraith_Portrait.webp",
    "Montagnard": "/killers/K03_TheHillbilly_Portrait.webp",
    "Infirmière": "/killers/K04_TheNurse_Portrait.webp",
    "Silhouette": "/killers/K05_TheShape_Portrait.webp",
    "Harpie": "/killers/K06_TheHag_Portrait.webp",
    "Docteur": "/killers/K07_TheDoctor_Portrait.webp",
    "Chasseuse": "/killers/K08_TheHuntress_Portrait.webp",
    "Cannibale": "/killers/K09_TheCannibal_Portrait.webp",
    "Cauchemar": "/killers/K10_TheNightmare_Portrait.webp",
    "Cochon": "/killers/K11_ThePig_Portrait.png",
    "Clown": "/killers/K12_TheClown_Portrait.webp",
    "Esprit": "/killers/K13_TheSpirit_Portrait.webp",
    "Légion": "/killers/K14_TheLegion_Portrait.webp",
    "Épidémie": "/killers/K15_ThePlague_Portrait.webp",
    "Ghost Face": "/killers/K16_TheGhostFace_Portrait.webp",
    "Démogorgon": "/killers/K17_TheDemogorgon_Portrait.webp",
    "Oni": "/killers/K18_TheOni_Portrait.webp",
    "Lance-Mort": "/killers/K19_TheDeathslinger_Portrait.webp",
    "Bourreau": "/killers/K20_TheExecutioner_Portrait.webp",
    "Fléau": "/killers/K21_TheBlight_Portrait.png",
    "Jumeaux": "/killers/K22_TheTwins_Portrait.webp",
    "Farceur": "/killers/K23_TheTrickster_Portrait.webp",
    "Némésis": "/killers/K24_TheNemesis_Portrait.webp",
    "Cénobite": "/killers/K25_TheCenobite_Portrait.webp",
    "Artiste": "/killers/K26_TheArtist_Portrait.webp",
    "Onryō": "/killers/K27_TheOnryo_Portrait.webp",
    "Dragage": "/killers/K28_TheDredge_Portrait.webp",
    "Mastermind": "/killers/K29_TheMastermind_Portrait.webp",
    "Chevalier": "/killers/K30_TheKnight_Portrait.webp",
    "Marchande de crânes": "/killers/K31_TheSkullMerchant_Portrait.webp",
    "Singularité": "/killers/K32_TheSingularity_Portrait.webp",
    "Xénomorphe": "/killers/K33_TheXenomorph_Portrait.webp",
    "Brave Gars": "/killers/K34_TheGoodGuy_Portrait.webp",
    "Inconnu": "/killers/K35_TheUnknown_Portrait.webp",
    "Liche": "/killers/K36_TheLich_Portrait.webp",
    "Seigneur des Ténèbres": "/killers/K37_TheDarkLord_Portrait.webp",
    "Maîtresse des Molosses": "/killers/K38_TheHoundmaster_Portrait.webp",
    "Le Premier": "/killers/K42_TheFirst_Portrait.png",
};

export const getKillerImage = (killerName: string) => {
    return KILLER_IMAGES[killerName] || null;
};

export const MAPS = [
    "Domaine MacMillan",
    "Décharge Autohaven",
    "Ferme Coldwind",
    "Asile de Crotus Prenn",
    "Haddonfield",
    "Marais de Backwater",
    "Institut de la Mémoire de Léry",
    "Forêt Rouge",
    "Springwood",
    "Usine Gideon",
    "Domaine Yamaoka",
    "Ormond",
    "Laboratoire d'Hawkins",
    "Saloon Dead Dawg",
    "École de Midwich",
    "Raccoon City",
    "Cimetière Abandonné",
    "Jardin de la Joie",
    "Place Dévastée",
    "Atterrissage de Toba",
    "Épave du Nostromo",
    "Place de Greenville",
    "Ruines Oubliées",
    "Freddy Fazbear's Pizza",
] as const;
